// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: locker/v1/internal.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInternalLockerServiceReleaseCell = "/locker.v1.InternalLockerService/ReleaseCell"
const OperationInternalLockerServiceReserveCell = "/locker.v1.InternalLockerService/ReserveCell"

type InternalLockerServiceHTTPServer interface {
	ReleaseCell(context.Context, *ReleaseCellRequest) (*ReleaseCellReply, error)
	ReserveCell(context.Context, *ReserveCellRequest) (*ReserveCellReply, error)
}

func RegisterInternalLockerServiceHTTPServer(s *http.Server, srv InternalLockerServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/internal/cells/reserve", _InternalLockerService_ReserveCell0_HTTP_Handler(srv))
	r.POST("/v1/internal/cells/{cell_id}/release", _InternalLockerService_ReleaseCell0_HTTP_Handler(srv))
}

func _InternalLockerService_ReserveCell0_HTTP_Handler(srv InternalLockerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReserveCellRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalLockerServiceReserveCell)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReserveCell(ctx, req.(*ReserveCellRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReserveCellReply)
		return ctx.Result(200, reply)
	}
}

func _InternalLockerService_ReleaseCell0_HTTP_Handler(srv InternalLockerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReleaseCellRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalLockerServiceReleaseCell)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReleaseCell(ctx, req.(*ReleaseCellRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReleaseCellReply)
		return ctx.Result(200, reply)
	}
}

type InternalLockerServiceHTTPClient interface {
	ReleaseCell(ctx context.Context, req *ReleaseCellRequest, opts ...http.CallOption) (rsp *ReleaseCellReply, err error)
	ReserveCell(ctx context.Context, req *ReserveCellRequest, opts ...http.CallOption) (rsp *ReserveCellReply, err error)
}

type InternalLockerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInternalLockerServiceHTTPClient(client *http.Client) InternalLockerServiceHTTPClient {
	return &InternalLockerServiceHTTPClientImpl{client}
}

func (c *InternalLockerServiceHTTPClientImpl) ReleaseCell(ctx context.Context, in *ReleaseCellRequest, opts ...http.CallOption) (*ReleaseCellReply, error) {
	var out ReleaseCellReply
	pattern := "/v1/internal/cells/{cell_id}/release"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInternalLockerServiceReleaseCell))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InternalLockerServiceHTTPClientImpl) ReserveCell(ctx context.Context, in *ReserveCellRequest, opts ...http.CallOption) (*ReserveCellReply, error) {
	var out ReserveCellReply
	pattern := "/v1/internal/cells/reserve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInternalLockerServiceReserveCell))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationInternalDeviceServiceCreateDeviceCommand = "/locker.v1.InternalDeviceService/CreateDeviceCommand"
const OperationInternalDeviceServiceGetDeviceCommand = "/locker.v1.InternalDeviceService/GetDeviceCommand"
const OperationInternalDeviceServiceHeartbeat = "/locker.v1.InternalDeviceService/Heartbeat"

type InternalDeviceServiceHTTPServer interface {
	CreateDeviceCommand(context.Context, *CreateDeviceCommandRequest) (*DeviceCommandReply, error)
	GetDeviceCommand(context.Context, *GetDeviceCommandRequest) (*DeviceCommandReply, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatReply, error)
}

func RegisterInternalDeviceServiceHTTPServer(s *http.Server, srv InternalDeviceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/internal/devices/{device_no}/heartbeat", _InternalDeviceService_Heartbeat0_HTTP_Handler(srv))
	r.POST("/v1/internal/device-commands", _InternalDeviceService_CreateDeviceCommand0_HTTP_Handler(srv))
	r.GET("/v1/internal/device-commands/{command_no}", _InternalDeviceService_GetDeviceCommand0_HTTP_Handler(srv))
}

func _InternalDeviceService_Heartbeat0_HTTP_Handler(srv InternalDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HeartbeatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalDeviceServiceHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Heartbeat(ctx, req.(*HeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HeartbeatReply)
		return ctx.Result(200, reply)
	}
}

func _InternalDeviceService_CreateDeviceCommand0_HTTP_Handler(srv InternalDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDeviceCommandRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalDeviceServiceCreateDeviceCommand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDeviceCommand(ctx, req.(*CreateDeviceCommandRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeviceCommandReply)
		return ctx.Result(200, reply)
	}
}

func _InternalDeviceService_GetDeviceCommand0_HTTP_Handler(srv InternalDeviceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeviceCommandRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalDeviceServiceGetDeviceCommand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeviceCommand(ctx, req.(*GetDeviceCommandRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeviceCommandReply)
		return ctx.Result(200, reply)
	}
}

type InternalDeviceServiceHTTPClient interface {
	CreateDeviceCommand(ctx context.Context, req *CreateDeviceCommandRequest, opts ...http.CallOption) (rsp *DeviceCommandReply, err error)
	GetDeviceCommand(ctx context.Context, req *GetDeviceCommandRequest, opts ...http.CallOption) (rsp *DeviceCommandReply, err error)
	Heartbeat(ctx context.Context, req *HeartbeatRequest, opts ...http.CallOption) (rsp *HeartbeatReply, err error)
}

type InternalDeviceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInternalDeviceServiceHTTPClient(client *http.Client) InternalDeviceServiceHTTPClient {
	return &InternalDeviceServiceHTTPClientImpl{client}
}

func (c *InternalDeviceServiceHTTPClientImpl) CreateDeviceCommand(ctx context.Context, in *CreateDeviceCommandRequest, opts ...http.CallOption) (*DeviceCommandReply, error) {
	var out DeviceCommandReply
	pattern := "/v1/internal/device-commands"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInternalDeviceServiceCreateDeviceCommand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InternalDeviceServiceHTTPClientImpl) GetDeviceCommand(ctx context.Context, in *GetDeviceCommandRequest, opts ...http.CallOption) (*DeviceCommandReply, error) {
	var out DeviceCommandReply
	pattern := "/v1/internal/device-commands/{command_no}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInternalDeviceServiceGetDeviceCommand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InternalDeviceServiceHTTPClientImpl) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...http.CallOption) (*HeartbeatReply, error) {
	var out HeartbeatReply
	pattern := "/v1/internal/devices/{device_no}/heartbeat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInternalDeviceServiceHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationInternalSimulatorServiceSetSimulatorScenario = "/locker.v1.InternalSimulatorService/SetSimulatorScenario"

type InternalSimulatorServiceHTTPServer interface {
	SetSimulatorScenario(context.Context, *SetSimulatorScenarioRequest) (*SetSimulatorScenarioReply, error)
}

func RegisterInternalSimulatorServiceHTTPServer(s *http.Server, srv InternalSimulatorServiceHTTPServer) {
	r := s.Route("/")
	r.PUT("/v1/internal/simulator/devices/{device_no}/scenario", _InternalSimulatorService_SetSimulatorScenario0_HTTP_Handler(srv))
}

func _InternalSimulatorService_SetSimulatorScenario0_HTTP_Handler(srv InternalSimulatorServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetSimulatorScenarioRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInternalSimulatorServiceSetSimulatorScenario)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetSimulatorScenario(ctx, req.(*SetSimulatorScenarioRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetSimulatorScenarioReply)
		return ctx.Result(200, reply)
	}
}

type InternalSimulatorServiceHTTPClient interface {
	SetSimulatorScenario(ctx context.Context, req *SetSimulatorScenarioRequest, opts ...http.CallOption) (rsp *SetSimulatorScenarioReply, err error)
}

type InternalSimulatorServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInternalSimulatorServiceHTTPClient(client *http.Client) InternalSimulatorServiceHTTPClient {
	return &InternalSimulatorServiceHTTPClientImpl{client}
}

func (c *InternalSimulatorServiceHTTPClientImpl) SetSimulatorScenario(ctx context.Context, in *SetSimulatorScenarioRequest, opts ...http.CallOption) (*SetSimulatorScenarioReply, error) {
	var out SetSimulatorScenarioReply
	pattern := "/v1/internal/simulator/devices/{device_no}/scenario"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInternalSimulatorServiceSetSimulatorScenario))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
