// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: locker/v1/internal.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceAction int32

const (
	DeviceAction_DEVICE_ACTION_UNSPECIFIED  DeviceAction = 0
	DeviceAction_DEVICE_ACTION_OPEN_DOOR    DeviceAction = 1
	DeviceAction_DEVICE_ACTION_QUERY_STATUS DeviceAction = 2
)

// Enum value maps for DeviceAction.
var (
	DeviceAction_name = map[int32]string{
		0: "DEVICE_ACTION_UNSPECIFIED",
		1: "DEVICE_ACTION_OPEN_DOOR",
		2: "DEVICE_ACTION_QUERY_STATUS",
	}
	DeviceAction_value = map[string]int32{
		"DEVICE_ACTION_UNSPECIFIED":  0,
		"DEVICE_ACTION_OPEN_DOOR":    1,
		"DEVICE_ACTION_QUERY_STATUS": 2,
	}
)

func (x DeviceAction) Enum() *DeviceAction {
	p := new(DeviceAction)
	*p = x
	return p
}

func (x DeviceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_internal_proto_enumTypes[0].Descriptor()
}

func (DeviceAction) Type() protoreflect.EnumType {
	return &file_locker_v1_internal_proto_enumTypes[0]
}

func (x DeviceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceAction.Descriptor instead.
func (DeviceAction) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{0}
}

type DeviceCommandStatus int32

const (
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_UNSPECIFIED DeviceCommandStatus = 0
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_PENDING     DeviceCommandStatus = 1
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_RUNNING     DeviceCommandStatus = 2
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_SUCCEEDED   DeviceCommandStatus = 3
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_FAILED      DeviceCommandStatus = 4
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_TIMED_OUT   DeviceCommandStatus = 5
	DeviceCommandStatus_DEVICE_COMMAND_STATUS_EXPIRED     DeviceCommandStatus = 6
)

// Enum value maps for DeviceCommandStatus.
var (
	DeviceCommandStatus_name = map[int32]string{
		0: "DEVICE_COMMAND_STATUS_UNSPECIFIED",
		1: "DEVICE_COMMAND_STATUS_PENDING",
		2: "DEVICE_COMMAND_STATUS_RUNNING",
		3: "DEVICE_COMMAND_STATUS_SUCCEEDED",
		4: "DEVICE_COMMAND_STATUS_FAILED",
		5: "DEVICE_COMMAND_STATUS_TIMED_OUT",
		6: "DEVICE_COMMAND_STATUS_EXPIRED",
	}
	DeviceCommandStatus_value = map[string]int32{
		"DEVICE_COMMAND_STATUS_UNSPECIFIED": 0,
		"DEVICE_COMMAND_STATUS_PENDING":     1,
		"DEVICE_COMMAND_STATUS_RUNNING":     2,
		"DEVICE_COMMAND_STATUS_SUCCEEDED":   3,
		"DEVICE_COMMAND_STATUS_FAILED":      4,
		"DEVICE_COMMAND_STATUS_TIMED_OUT":   5,
		"DEVICE_COMMAND_STATUS_EXPIRED":     6,
	}
)

func (x DeviceCommandStatus) Enum() *DeviceCommandStatus {
	p := new(DeviceCommandStatus)
	*p = x
	return p
}

func (x DeviceCommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_internal_proto_enumTypes[1].Descriptor()
}

func (DeviceCommandStatus) Type() protoreflect.EnumType {
	return &file_locker_v1_internal_proto_enumTypes[1]
}

func (x DeviceCommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCommandStatus.Descriptor instead.
func (DeviceCommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{1}
}

type SimulatorScenario int32

const (
	SimulatorScenario_SIMULATOR_SCENARIO_UNSPECIFIED    SimulatorScenario = 0
	SimulatorScenario_SIMULATOR_SCENARIO_ONLINE         SimulatorScenario = 1
	SimulatorScenario_SIMULATOR_SCENARIO_OFFLINE        SimulatorScenario = 2
	SimulatorScenario_SIMULATOR_SCENARIO_TIMEOUT        SimulatorScenario = 3
	SimulatorScenario_SIMULATOR_SCENARIO_FAIL           SimulatorScenario = 4
	SimulatorScenario_SIMULATOR_SCENARIO_DOOR_LEFT_OPEN SimulatorScenario = 5
)

// Enum value maps for SimulatorScenario.
var (
	SimulatorScenario_name = map[int32]string{
		0: "SIMULATOR_SCENARIO_UNSPECIFIED",
		1: "SIMULATOR_SCENARIO_ONLINE",
		2: "SIMULATOR_SCENARIO_OFFLINE",
		3: "SIMULATOR_SCENARIO_TIMEOUT",
		4: "SIMULATOR_SCENARIO_FAIL",
		5: "SIMULATOR_SCENARIO_DOOR_LEFT_OPEN",
	}
	SimulatorScenario_value = map[string]int32{
		"SIMULATOR_SCENARIO_UNSPECIFIED":    0,
		"SIMULATOR_SCENARIO_ONLINE":         1,
		"SIMULATOR_SCENARIO_OFFLINE":        2,
		"SIMULATOR_SCENARIO_TIMEOUT":        3,
		"SIMULATOR_SCENARIO_FAIL":           4,
		"SIMULATOR_SCENARIO_DOOR_LEFT_OPEN": 5,
	}
)

func (x SimulatorScenario) Enum() *SimulatorScenario {
	p := new(SimulatorScenario)
	*p = x
	return p
}

func (x SimulatorScenario) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulatorScenario) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_internal_proto_enumTypes[2].Descriptor()
}

func (SimulatorScenario) Type() protoreflect.EnumType {
	return &file_locker_v1_internal_proto_enumTypes[2]
}

func (x SimulatorScenario) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulatorScenario.Descriptor instead.
func (SimulatorScenario) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{2}
}

type ReserveCellRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SiteId         string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Size           CellSize               `protobuf:"varint,2,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	TtlSeconds     int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveCellRequest) Reset() {
	*x = ReserveCellRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCellRequest) ProtoMessage() {}

func (x *ReserveCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCellRequest.ProtoReflect.Descriptor instead.
func (*ReserveCellRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveCellRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ReserveCellRequest) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *ReserveCellRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ReserveCellRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveCellReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	DeviceNo      string                 `protobuf:"bytes,2,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	CellNo        string                 `protobuf:"bytes,3,opt,name=cell_no,json=cellNo,proto3" json:"cell_no,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCellReply) Reset() {
	*x = ReserveCellReply{}
	mi := &file_locker_v1_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCellReply) ProtoMessage() {}

func (x *ReserveCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCellReply.ProtoReflect.Descriptor instead.
func (*ReserveCellReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveCellReply) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ReserveCellReply) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *ReserveCellReply) GetCellNo() string {
	if x != nil {
		return x.CellNo
	}
	return ""
}

func (x *ReserveCellReply) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ReleaseCellRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CellId         string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseCellRequest) Reset() {
	*x = ReleaseCellRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCellRequest) ProtoMessage() {}

func (x *ReleaseCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCellRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCellRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ReleaseCellRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReleaseCellReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCellReply) Reset() {
	*x = ReleaseCellReply{}
	mi := &file_locker_v1_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCellReply) ProtoMessage() {}

func (x *ReleaseCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCellReply.ProtoReflect.Descriptor instead.
func (*ReleaseCellReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseCellReply) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo        string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,2,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	ReportedAt      string                 `protobuf:"bytes,3,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	Online          bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *HeartbeatRequest) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

func (x *HeartbeatRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedAt    string                 `protobuf:"bytes,1,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_locker_v1_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatReply) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

type CreateDeviceCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo       string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	Action         DeviceAction           `protobuf:"varint,2,opt,name=action,proto3,enum=locker.v1.DeviceAction" json:"action,omitempty"`
	CellNo         string                 `protobuf:"bytes,3,opt,name=cell_no,json=cellNo,proto3" json:"cell_no,omitempty"`
	TtlSeconds     int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDeviceCommandRequest) Reset() {
	*x = CreateDeviceCommandRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceCommandRequest) ProtoMessage() {}

func (x *CreateDeviceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceCommandRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDeviceCommandRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *CreateDeviceCommandRequest) GetAction() DeviceAction {
	if x != nil {
		return x.Action
	}
	return DeviceAction_DEVICE_ACTION_UNSPECIFIED
}

func (x *CreateDeviceCommandRequest) GetCellNo() string {
	if x != nil {
		return x.CellNo
	}
	return ""
}

func (x *CreateDeviceCommandRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateDeviceCommandRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetDeviceCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandNo     string                 `protobuf:"bytes,1,opt,name=command_no,json=commandNo,proto3" json:"command_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceCommandRequest) Reset() {
	*x = GetDeviceCommandRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceCommandRequest) ProtoMessage() {}

func (x *GetDeviceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceCommandRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceCommandRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceCommandRequest) GetCommandNo() string {
	if x != nil {
		return x.CommandNo
	}
	return ""
}

type DeviceCommandReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandNo     string                 `protobuf:"bytes,1,opt,name=command_no,json=commandNo,proto3" json:"command_no,omitempty"`
	Status        DeviceCommandStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=locker.v1.DeviceCommandStatus" json:"status,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	DoorOpened    bool                   `protobuf:"varint,4,opt,name=door_opened,json=doorOpened,proto3" json:"door_opened,omitempty"`
	DoorClosed    bool                   `protobuf:"varint,5,opt,name=door_closed,json=doorClosed,proto3" json:"door_closed,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCommandReply) Reset() {
	*x = DeviceCommandReply{}
	mi := &file_locker_v1_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCommandReply) ProtoMessage() {}

func (x *DeviceCommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCommandReply.ProtoReflect.Descriptor instead.
func (*DeviceCommandReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceCommandReply) GetCommandNo() string {
	if x != nil {
		return x.CommandNo
	}
	return ""
}

func (x *DeviceCommandReply) GetStatus() DeviceCommandStatus {
	if x != nil {
		return x.Status
	}
	return DeviceCommandStatus_DEVICE_COMMAND_STATUS_UNSPECIFIED
}

func (x *DeviceCommandReply) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *DeviceCommandReply) GetDoorOpened() bool {
	if x != nil {
		return x.DoorOpened
	}
	return false
}

func (x *DeviceCommandReply) GetDoorClosed() bool {
	if x != nil {
		return x.DoorClosed
	}
	return false
}

func (x *DeviceCommandReply) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SetSimulatorScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceNo      string                 `protobuf:"bytes,1,opt,name=device_no,json=deviceNo,proto3" json:"device_no,omitempty"`
	Scenario      SimulatorScenario      `protobuf:"varint,2,opt,name=scenario,proto3,enum=locker.v1.SimulatorScenario" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSimulatorScenarioRequest) Reset() {
	*x = SetSimulatorScenarioRequest{}
	mi := &file_locker_v1_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSimulatorScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSimulatorScenarioRequest) ProtoMessage() {}

func (x *SetSimulatorScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSimulatorScenarioRequest.ProtoReflect.Descriptor instead.
func (*SetSimulatorScenarioRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{9}
}

func (x *SetSimulatorScenarioRequest) GetDeviceNo() string {
	if x != nil {
		return x.DeviceNo
	}
	return ""
}

func (x *SetSimulatorScenarioRequest) GetScenario() SimulatorScenario {
	if x != nil {
		return x.Scenario
	}
	return SimulatorScenario_SIMULATOR_SCENARIO_UNSPECIFIED
}

type SetSimulatorScenarioReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSimulatorScenarioReply) Reset() {
	*x = SetSimulatorScenarioReply{}
	mi := &file_locker_v1_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSimulatorScenarioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSimulatorScenarioReply) ProtoMessage() {}

func (x *SetSimulatorScenarioReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSimulatorScenarioReply.ProtoReflect.Descriptor instead.
func (*SetSimulatorScenarioReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_internal_proto_rawDescGZIP(), []int{10}
}

func (x *SetSimulatorScenarioReply) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_locker_v1_internal_proto protoreflect.FileDescriptor

const file_locker_v1_internal_proto_rawDesc = "" +
	"\n" +
	"\x18locker/v1/internal.proto\x12\tlocker.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14locker/v1/site.proto\"\xa0\x01\n" +
	"\x12ReserveCellRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12'\n" +
	"\x04size\x18\x02 \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\x80\x01\n" +
	"\x10ReserveCellReply\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1b\n" +
	"\tdevice_no\x18\x02 \x01(\tR\bdeviceNo\x12\x17\n" +
	"\acell_no\x18\x03 \x01(\tR\x06cellNo\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"V\n" +
	"\x12ReleaseCellRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\".\n" +
	"\x10ReleaseCellReply\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\x93\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tdevice_no\x18\x01 \x01(\tR\bdeviceNo\x12)\n" +
	"\x10firmware_version\x18\x02 \x01(\tR\x0ffirmwareVersion\x12\x1f\n" +
	"\vreported_at\x18\x03 \x01(\tR\n" +
	"reportedAt\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\"1\n" +
	"\x0eHeartbeatReply\x12\x1f\n" +
	"\vaccepted_at\x18\x01 \x01(\tR\n" +
	"acceptedAt\"\xcd\x01\n" +
	"\x1aCreateDeviceCommandRequest\x12\x1b\n" +
	"\tdevice_no\x18\x01 \x01(\tR\bdeviceNo\x12/\n" +
	"\x06action\x18\x02 \x01(\x0e2\x17.locker.v1.DeviceActionR\x06action\x12\x17\n" +
	"\acell_no\x18\x03 \x01(\tR\x06cellNo\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"8\n" +
	"\x17GetDeviceCommandRequest\x12\x1d\n" +
	"\n" +
	"command_no\x18\x01 \x01(\tR\tcommandNo\"\xea\x01\n" +
	"\x12DeviceCommandReply\x12\x1d\n" +
	"\n" +
	"command_no\x18\x01 \x01(\tR\tcommandNo\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.locker.v1.DeviceCommandStatusR\x06status\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12\x1f\n" +
	"\vdoor_opened\x18\x04 \x01(\bR\n" +
	"doorOpened\x12\x1f\n" +
	"\vdoor_closed\x18\x05 \x01(\bR\n" +
	"doorClosed\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\"t\n" +
	"\x1bSetSimulatorScenarioRequest\x12\x1b\n" +
	"\tdevice_no\x18\x01 \x01(\tR\bdeviceNo\x128\n" +
	"\bscenario\x18\x02 \x01(\x0e2\x1c.locker.v1.SimulatorScenarioR\bscenario\"5\n" +
	"\x19SetSimulatorScenarioReply\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated*j\n" +
	"\fDeviceAction\x12\x1d\n" +
	"\x19DEVICE_ACTION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEVICE_ACTION_OPEN_DOOR\x10\x01\x12\x1e\n" +
	"\x1aDEVICE_ACTION_QUERY_STATUS\x10\x02*\x91\x02\n" +
	"\x13DeviceCommandStatus\x12%\n" +
	"!DEVICE_COMMAND_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDEVICE_COMMAND_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dDEVICE_COMMAND_STATUS_RUNNING\x10\x02\x12#\n" +
	"\x1fDEVICE_COMMAND_STATUS_SUCCEEDED\x10\x03\x12 \n" +
	"\x1cDEVICE_COMMAND_STATUS_FAILED\x10\x04\x12#\n" +
	"\x1fDEVICE_COMMAND_STATUS_TIMED_OUT\x10\x05\x12!\n" +
	"\x1dDEVICE_COMMAND_STATUS_EXPIRED\x10\x06*\xda\x01\n" +
	"\x11SimulatorScenario\x12\"\n" +
	"\x1eSIMULATOR_SCENARIO_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SIMULATOR_SCENARIO_ONLINE\x10\x01\x12\x1e\n" +
	"\x1aSIMULATOR_SCENARIO_OFFLINE\x10\x02\x12\x1e\n" +
	"\x1aSIMULATOR_SCENARIO_TIMEOUT\x10\x03\x12\x1b\n" +
	"\x17SIMULATOR_SCENARIO_FAIL\x10\x04\x12%\n" +
	"!SIMULATOR_SCENARIO_DOOR_LEFT_OPEN\x10\x052\x85\x02\n" +
	"\x15InternalLockerService\x12p\n" +
	"\vReserveCell\x12\x1d.locker.v1.ReserveCellRequest\x1a\x1b.locker.v1.ReserveCellReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/internal/cells/reserve\x12z\n" +
	"\vReleaseCell\x12\x1d.locker.v1.ReleaseCellRequest\x1a\x1b.locker.v1.ReleaseCellReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/internal/cells/{cell_id}/release2\xa5\x03\n" +
	"\x15InternalDeviceService\x12z\n" +
	"\tHeartbeat\x12\x1b.locker.v1.HeartbeatRequest\x1a\x19.locker.v1.HeartbeatReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/internal/devices/{device_no}/heartbeat\x12\x84\x01\n" +
	"\x13CreateDeviceCommand\x12%.locker.v1.CreateDeviceCommandRequest\x1a\x1d.locker.v1.DeviceCommandReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/internal/device-commands\x12\x88\x01\n" +
	"\x10GetDeviceCommand\x12\".locker.v1.GetDeviceCommandRequest\x1a\x1d.locker.v1.DeviceCommandReply\"1\x82\xd3\xe4\x93\x02+\x12)/v1/internal/device-commands/{command_no}2\xc1\x01\n" +
	"\x18InternalSimulatorService\x12\xa4\x01\n" +
	"\x14SetSimulatorScenario\x12&.locker.v1.SetSimulatorScenarioRequest\x1a$.locker.v1.SetSimulatorScenarioReply\">\x82\xd3\xe4\x93\x028:\x01*\x1a3/v1/internal/simulator/devices/{device_no}/scenarioB?Z=github.com/rjt001124-dev/smart-parcel-locker/api/locker/v1;v1b\x06proto3"

var (
	file_locker_v1_internal_proto_rawDescOnce sync.Once
	file_locker_v1_internal_proto_rawDescData []byte
)

func file_locker_v1_internal_proto_rawDescGZIP() []byte {
	file_locker_v1_internal_proto_rawDescOnce.Do(func() {
		file_locker_v1_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locker_v1_internal_proto_rawDesc), len(file_locker_v1_internal_proto_rawDesc)))
	})
	return file_locker_v1_internal_proto_rawDescData
}

var file_locker_v1_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_locker_v1_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_locker_v1_internal_proto_goTypes = []any{
	(DeviceAction)(0),                   // 0: locker.v1.DeviceAction
	(DeviceCommandStatus)(0),            // 1: locker.v1.DeviceCommandStatus
	(SimulatorScenario)(0),              // 2: locker.v1.SimulatorScenario
	(*ReserveCellRequest)(nil),          // 3: locker.v1.ReserveCellRequest
	(*ReserveCellReply)(nil),            // 4: locker.v1.ReserveCellReply
	(*ReleaseCellRequest)(nil),          // 5: locker.v1.ReleaseCellRequest
	(*ReleaseCellReply)(nil),            // 6: locker.v1.ReleaseCellReply
	(*HeartbeatRequest)(nil),            // 7: locker.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),              // 8: locker.v1.HeartbeatReply
	(*CreateDeviceCommandRequest)(nil),  // 9: locker.v1.CreateDeviceCommandRequest
	(*GetDeviceCommandRequest)(nil),     // 10: locker.v1.GetDeviceCommandRequest
	(*DeviceCommandReply)(nil),          // 11: locker.v1.DeviceCommandReply
	(*SetSimulatorScenarioRequest)(nil), // 12: locker.v1.SetSimulatorScenarioRequest
	(*SetSimulatorScenarioReply)(nil),   // 13: locker.v1.SetSimulatorScenarioReply
	(CellSize)(0),                       // 14: locker.v1.CellSize
}
var file_locker_v1_internal_proto_depIdxs = []int32{
	14, // 0: locker.v1.ReserveCellRequest.size:type_name -> locker.v1.CellSize
	0,  // 1: locker.v1.CreateDeviceCommandRequest.action:type_name -> locker.v1.DeviceAction
	1,  // 2: locker.v1.DeviceCommandReply.status:type_name -> locker.v1.DeviceCommandStatus
	2,  // 3: locker.v1.SetSimulatorScenarioRequest.scenario:type_name -> locker.v1.SimulatorScenario
	3,  // 4: locker.v1.InternalLockerService.ReserveCell:input_type -> locker.v1.ReserveCellRequest
	5,  // 5: locker.v1.InternalLockerService.ReleaseCell:input_type -> locker.v1.ReleaseCellRequest
	7,  // 6: locker.v1.InternalDeviceService.Heartbeat:input_type -> locker.v1.HeartbeatRequest
	9,  // 7: locker.v1.InternalDeviceService.CreateDeviceCommand:input_type -> locker.v1.CreateDeviceCommandRequest
	10, // 8: locker.v1.InternalDeviceService.GetDeviceCommand:input_type -> locker.v1.GetDeviceCommandRequest
	12, // 9: locker.v1.InternalSimulatorService.SetSimulatorScenario:input_type -> locker.v1.SetSimulatorScenarioRequest
	4,  // 10: locker.v1.InternalLockerService.ReserveCell:output_type -> locker.v1.ReserveCellReply
	6,  // 11: locker.v1.InternalLockerService.ReleaseCell:output_type -> locker.v1.ReleaseCellReply
	8,  // 12: locker.v1.InternalDeviceService.Heartbeat:output_type -> locker.v1.HeartbeatReply
	11, // 13: locker.v1.InternalDeviceService.CreateDeviceCommand:output_type -> locker.v1.DeviceCommandReply
	11, // 14: locker.v1.InternalDeviceService.GetDeviceCommand:output_type -> locker.v1.DeviceCommandReply
	13, // 15: locker.v1.InternalSimulatorService.SetSimulatorScenario:output_type -> locker.v1.SetSimulatorScenarioReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_locker_v1_internal_proto_init() }
func file_locker_v1_internal_proto_init() {
	if File_locker_v1_internal_proto != nil {
		return
	}
	file_locker_v1_site_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locker_v1_internal_proto_rawDesc), len(file_locker_v1_internal_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_locker_v1_internal_proto_goTypes,
		DependencyIndexes: file_locker_v1_internal_proto_depIdxs,
		EnumInfos:         file_locker_v1_internal_proto_enumTypes,
		MessageInfos:      file_locker_v1_internal_proto_msgTypes,
	}.Build()
	File_locker_v1_internal_proto = out.File
	file_locker_v1_internal_proto_goTypes = nil
	file_locker_v1_internal_proto_depIdxs = nil
}
