// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: locker/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderServiceCancelOrder = "/locker.v1.OrderService/CancelOrder"
const OperationOrderServiceConfirmDevelopmentPayment = "/locker.v1.OrderService/ConfirmDevelopmentPayment"
const OperationOrderServiceCreateOrder = "/locker.v1.OrderService/CreateOrder"
const OperationOrderServiceGetOrder = "/locker.v1.OrderService/GetOrder"
const OperationOrderServiceListOrders = "/locker.v1.OrderService/ListOrders"
const OperationOrderServiceOpenDepositDoor = "/locker.v1.OrderService/OpenDepositDoor"
const OperationOrderServiceOpenPickupDoor = "/locker.v1.OrderService/OpenPickupDoor"
const OperationOrderServiceSettleOverdue = "/locker.v1.OrderService/SettleOverdue"

type OrderServiceHTTPServer interface {
	CancelOrder(context.Context, *CancelOrderRequest) (*OrderReply, error)
	// ConfirmDevelopmentPayment Development-only payment simulator. Rejected unless APP_ENV=development.
	ConfirmDevelopmentPayment(context.Context, *ConfirmDevelopmentPaymentRequest) (*OrderReply, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*OrderReply, error)
	GetOrder(context.Context, *GetOrderRequest) (*OrderReply, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersReply, error)
	// OpenDepositDoor Requests the locker door to open so the parcel can be deposited.
	// Only valid when the order status is AWAITING_DEPOSIT.
	OpenDepositDoor(context.Context, *OpenDepositDoorRequest) (*OrderReply, error)
	// OpenPickupDoor Requests the locker door to open so the parcel can be picked up.
	// Only valid when the order status is IN_STORAGE or AWAITING_PICKUP and
	// the order is not overdue.
	OpenPickupDoor(context.Context, *OpenPickupDoorRequest) (*OrderReply, error)
	// SettleOverdue Development-only overdue settlement simulator. Rejected unless APP_ENV=development.
	SettleOverdue(context.Context, *SettleOverdueRequest) (*OrderReply, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/orders", _OrderService_CreateOrder0_HTTP_Handler(srv))
	r.GET("/v1/orders/{order_id}", _OrderService_GetOrder0_HTTP_Handler(srv))
	r.GET("/v1/orders", _OrderService_ListOrders0_HTTP_Handler(srv))
	r.POST("/v1/orders/{order_id}/cancellations", _OrderService_CancelOrder0_HTTP_Handler(srv))
	r.POST("/v1/orders/{order_id}/deposit-door-requests", _OrderService_OpenDepositDoor0_HTTP_Handler(srv))
	r.POST("/v1/orders/{order_id}/pickup-door-requests", _OrderService_OpenPickupDoor0_HTTP_Handler(srv))
	r.POST("/v1/development/orders/{order_id}/payment-confirmations", _OrderService_ConfirmDevelopmentPayment0_HTTP_Handler(srv))
	r.POST("/v1/development/orders/{order_id}/overdue-payments", _OrderService_SettleOverdue0_HTTP_Handler(srv))
}

func _OrderService_CreateOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCreateOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_CancelOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCancelOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelOrder(ctx, req.(*CancelOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_OpenDepositDoor0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenDepositDoorRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceOpenDepositDoor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenDepositDoor(ctx, req.(*OpenDepositDoorRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_OpenPickupDoor0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenPickupDoorRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceOpenPickupDoor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenPickupDoor(ctx, req.(*OpenPickupDoorRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ConfirmDevelopmentPayment0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmDevelopmentPaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceConfirmDevelopmentPayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmDevelopmentPayment(ctx, req.(*ConfirmDevelopmentPaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

func _OrderService_SettleOverdue0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SettleOverdueRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceSettleOverdue)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SettleOverdue(ctx, req.(*SettleOverdueRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderReply)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	CancelOrder(ctx context.Context, req *CancelOrderRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	// ConfirmDevelopmentPayment Development-only payment simulator. Rejected unless APP_ENV=development.
	ConfirmDevelopmentPayment(ctx context.Context, req *ConfirmDevelopmentPaymentRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	CreateOrder(ctx context.Context, req *CreateOrderRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	GetOrder(ctx context.Context, req *GetOrderRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersReply, err error)
	// OpenDepositDoor Requests the locker door to open so the parcel can be deposited.
	// Only valid when the order status is AWAITING_DEPOSIT.
	OpenDepositDoor(ctx context.Context, req *OpenDepositDoorRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	// OpenPickupDoor Requests the locker door to open so the parcel can be picked up.
	// Only valid when the order status is IN_STORAGE or AWAITING_PICKUP and
	// the order is not overdue.
	OpenPickupDoor(ctx context.Context, req *OpenPickupDoorRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
	// SettleOverdue Development-only overdue settlement simulator. Rejected unless APP_ENV=development.
	SettleOverdue(ctx context.Context, req *SettleOverdueRequest, opts ...http.CallOption) (rsp *OrderReply, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/orders/{order_id}/cancellations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCancelOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConfirmDevelopmentPayment Development-only payment simulator. Rejected unless APP_ENV=development.
func (c *OrderServiceHTTPClientImpl) ConfirmDevelopmentPayment(ctx context.Context, in *ConfirmDevelopmentPaymentRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/development/orders/{order_id}/payment-confirmations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceConfirmDevelopmentPayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceCreateOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/orders/{order_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceGetOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersReply, error) {
	var out ListOrdersReply
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderServiceListOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OpenDepositDoor Requests the locker door to open so the parcel can be deposited.
// Only valid when the order status is AWAITING_DEPOSIT.
func (c *OrderServiceHTTPClientImpl) OpenDepositDoor(ctx context.Context, in *OpenDepositDoorRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/orders/{order_id}/deposit-door-requests"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceOpenDepositDoor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// OpenPickupDoor Requests the locker door to open so the parcel can be picked up.
// Only valid when the order status is IN_STORAGE or AWAITING_PICKUP and
// the order is not overdue.
func (c *OrderServiceHTTPClientImpl) OpenPickupDoor(ctx context.Context, in *OpenPickupDoorRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/orders/{order_id}/pickup-door-requests"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceOpenPickupDoor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SettleOverdue Development-only overdue settlement simulator. Rejected unless APP_ENV=development.
func (c *OrderServiceHTTPClientImpl) SettleOverdue(ctx context.Context, in *SettleOverdueRequest, opts ...http.CallOption) (*OrderReply, error) {
	var out OrderReply
	pattern := "/v1/development/orders/{order_id}/overdue-payments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderServiceSettleOverdue))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
