// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: locker/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING_PAYMENT  OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID             OrderStatus = 2
	OrderStatus_ORDER_STATUS_AWAITING_DEPOSIT OrderStatus = 3
	OrderStatus_ORDER_STATUS_IN_STORAGE       OrderStatus = 4
	OrderStatus_ORDER_STATUS_AWAITING_PICKUP  OrderStatus = 5
	OrderStatus_ORDER_STATUS_OVERDUE          OrderStatus = 6
	OrderStatus_ORDER_STATUS_COMPLETED        OrderStatus = 7
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 8
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING_PAYMENT",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_AWAITING_DEPOSIT",
		4: "ORDER_STATUS_IN_STORAGE",
		5: "ORDER_STATUS_AWAITING_PICKUP",
		6: "ORDER_STATUS_OVERDUE",
		7: "ORDER_STATUS_COMPLETED",
		8: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_PENDING_PAYMENT":  1,
		"ORDER_STATUS_PAID":             2,
		"ORDER_STATUS_AWAITING_DEPOSIT": 3,
		"ORDER_STATUS_IN_STORAGE":       4,
		"ORDER_STATUS_AWAITING_PICKUP":  5,
		"ORDER_STATUS_OVERDUE":          6,
		"ORDER_STATUS_COMPLETED":        7,
		"ORDER_STATUS_CANCELLED":        8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_locker_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{0}
}

// All money fields are integer fen (分). Floating point is forbidden.
type FeeSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentFeeFen    int64                  `protobuf:"varint,1,opt,name=rent_fee_fen,json=rentFeeFen,proto3" json:"rent_fee_fen,omitempty"`
	DepositFen    int64                  `protobuf:"varint,2,opt,name=deposit_fen,json=depositFen,proto3" json:"deposit_fen,omitempty"`
	DiscountFen   int64                  `protobuf:"varint,3,opt,name=discount_fen,json=discountFen,proto3" json:"discount_fen,omitempty"`
	TotalFen      int64                  `protobuf:"varint,4,opt,name=total_fen,json=totalFen,proto3" json:"total_fen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeSnapshot) Reset() {
	*x = FeeSnapshot{}
	mi := &file_locker_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeSnapshot) ProtoMessage() {}

func (x *FeeSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeSnapshot.ProtoReflect.Descriptor instead.
func (*FeeSnapshot) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *FeeSnapshot) GetRentFeeFen() int64 {
	if x != nil {
		return x.RentFeeFen
	}
	return 0
}

func (x *FeeSnapshot) GetDepositFen() int64 {
	if x != nil {
		return x.DepositFen
	}
	return 0
}

func (x *FeeSnapshot) GetDiscountFen() int64 {
	if x != nil {
		return x.DiscountFen
	}
	return 0
}

func (x *FeeSnapshot) GetTotalFen() int64 {
	if x != nil {
		return x.TotalFen
	}
	return 0
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo         string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	SiteId          string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	SiteName        string                 `protobuf:"bytes,4,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	CellId          string                 `protobuf:"bytes,5,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	CellNo          string                 `protobuf:"bytes,6,opt,name=cell_no,json=cellNo,proto3" json:"cell_no,omitempty"`
	Size            CellSize               `protobuf:"varint,7,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	Status          OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=locker.v1.OrderStatus" json:"status,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,9,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	FeeSnapshot     *FeeSnapshot           `protobuf:"bytes,10,opt,name=fee_snapshot,json=feeSnapshot,proto3" json:"fee_snapshot,omitempty"`
	// Extra amount currently due for an overdue order, integer fen.
	OverdueFeeFen int64  `protobuf:"varint,11,opt,name=overdue_fee_fen,json=overdueFeeFen,proto3" json:"overdue_fee_fen,omitempty"`
	CreatedAt     string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        string `protobuf:"bytes,13,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	DepositedAt   string `protobuf:"bytes,14,opt,name=deposited_at,json=depositedAt,proto3" json:"deposited_at,omitempty"`
	ExpiresAt     string `protobuf:"bytes,15,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CompletedAt   string `protobuf:"bytes,16,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_locker_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Order) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *Order) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *Order) GetCellNo() string {
	if x != nil {
		return x.CellNo
	}
	return ""
}

func (x *Order) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Order) GetFeeSnapshot() *FeeSnapshot {
	if x != nil {
		return x.FeeSnapshot
	}
	return nil
}

func (x *Order) GetOverdueFeeFen() int64 {
	if x != nil {
		return x.OverdueFeeFen
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Order) GetDepositedAt() string {
	if x != nil {
		return x.DepositedAt
	}
	return ""
}

func (x *Order) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Order) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SiteId          string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Size            CellSize               `protobuf:"varint,2,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *CreateOrderRequest) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{4}
}

type ListOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReply) Reset() {
	*x = ListOrdersReply{}
	mi := &file_locker_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReply) ProtoMessage() {}

func (x *ListOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReply.ProtoReflect.Descriptor instead.
func (*ListOrdersReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersReply) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OpenDepositDoorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDepositDoorRequest) Reset() {
	*x = OpenDepositDoorRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDepositDoorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDepositDoorRequest) ProtoMessage() {}

func (x *OpenDepositDoorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDepositDoorRequest.ProtoReflect.Descriptor instead.
func (*OpenDepositDoorRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *OpenDepositDoorRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OpenPickupDoorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPickupDoorRequest) Reset() {
	*x = OpenPickupDoorRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPickupDoorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPickupDoorRequest) ProtoMessage() {}

func (x *OpenPickupDoorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPickupDoorRequest.ProtoReflect.Descriptor instead.
func (*OpenPickupDoorRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *OpenPickupDoorRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ConfirmDevelopmentPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDevelopmentPaymentRequest) Reset() {
	*x = ConfirmDevelopmentPaymentRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDevelopmentPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDevelopmentPaymentRequest) ProtoMessage() {}

func (x *ConfirmDevelopmentPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDevelopmentPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDevelopmentPaymentRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmDevelopmentPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type SettleOverdueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleOverdueRequest) Reset() {
	*x = SettleOverdueRequest{}
	mi := &file_locker_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleOverdueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleOverdueRequest) ProtoMessage() {}

func (x *SettleOverdueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleOverdueRequest.ProtoReflect.Descriptor instead.
func (*SettleOverdueRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *SettleOverdueRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderReply) Reset() {
	*x = OrderReply{}
	mi := &file_locker_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReply) ProtoMessage() {}

func (x *OrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReply.ProtoReflect.Descriptor instead.
func (*OrderReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderReply) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_locker_v1_order_proto protoreflect.FileDescriptor

const file_locker_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x15locker/v1/order.proto\x12\tlocker.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14locker/v1/site.proto\"\x90\x01\n" +
	"\vFeeSnapshot\x12 \n" +
	"\frent_fee_fen\x18\x01 \x01(\x03R\n" +
	"rentFeeFen\x12\x1f\n" +
	"\vdeposit_fen\x18\x02 \x01(\x03R\n" +
	"depositFen\x12!\n" +
	"\fdiscount_fen\x18\x03 \x01(\x03R\vdiscountFen\x12\x1b\n" +
	"\ttotal_fen\x18\x04 \x01(\x03R\btotalFen\"\x9e\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x1b\n" +
	"\tsite_name\x18\x04 \x01(\tR\bsiteName\x12\x17\n" +
	"\acell_id\x18\x05 \x01(\tR\x06cellId\x12\x17\n" +
	"\acell_no\x18\x06 \x01(\tR\x06cellNo\x12'\n" +
	"\x04size\x18\a \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.locker.v1.OrderStatusR\x06status\x12)\n" +
	"\x10duration_minutes\x18\t \x01(\x05R\x0fdurationMinutes\x129\n" +
	"\ffee_snapshot\x18\n" +
	" \x01(\v2\x16.locker.v1.FeeSnapshotR\vfeeSnapshot\x12&\n" +
	"\x0foverdue_fee_fen\x18\v \x01(\x03R\roverdueFeeFen\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\r \x01(\tR\x06paidAt\x12!\n" +
	"\fdeposited_at\x18\x0e \x01(\tR\vdepositedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0f \x01(\tR\texpiresAt\x12!\n" +
	"\fcompleted_at\x18\x10 \x01(\tR\vcompletedAt\"\x81\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12'\n" +
	"\x04size\x18\x02 \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x13\n" +
	"\x11ListOrdersRequest\";\n" +
	"\x0fListOrdersReply\x12(\n" +
	"\x06orders\x18\x01 \x03(\v2\x10.locker.v1.OrderR\x06orders\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"3\n" +
	"\x16OpenDepositDoorRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"2\n" +
	"\x15OpenPickupDoorRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"=\n" +
	" ConfirmDevelopmentPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"1\n" +
	"\x14SettleOverdueRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"4\n" +
	"\n" +
	"OrderReply\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.locker.v1.OrderR\x05order*\x98\x02\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cORDER_STATUS_PENDING_PAYMENT\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12!\n" +
	"\x1dORDER_STATUS_AWAITING_DEPOSIT\x10\x03\x12\x1b\n" +
	"\x17ORDER_STATUS_IN_STORAGE\x10\x04\x12 \n" +
	"\x1cORDER_STATUS_AWAITING_PICKUP\x10\x05\x12\x18\n" +
	"\x14ORDER_STATUS_OVERDUE\x10\x06\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\a\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\b2\xd1\a\n" +
	"\fOrderService\x12Z\n" +
	"\vCreateOrder\x12\x1d.locker.v1.CreateOrderRequest\x1a\x15.locker.v1.OrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12\\\n" +
	"\bGetOrder\x12\x1a.locker.v1.GetOrderRequest\x1a\x15.locker.v1.OrderReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12Z\n" +
	"\n" +
	"ListOrders\x12\x1c.locker.v1.ListOrdersRequest\x1a\x1a.locker.v1.ListOrdersReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12s\n" +
	"\vCancelOrder\x12\x1d.locker.v1.CancelOrderRequest\x1a\x15.locker.v1.OrderReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/orders/{order_id}/cancellations\x12\x83\x01\n" +
	"\x0fOpenDepositDoor\x12!.locker.v1.OpenDepositDoorRequest\x1a\x15.locker.v1.OrderReply\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/orders/{order_id}/deposit-door-requests\x12\x80\x01\n" +
	"\x0eOpenPickupDoor\x12 .locker.v1.OpenPickupDoorRequest\x1a\x15.locker.v1.OrderReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/orders/{order_id}/pickup-door-requests\x12\xa3\x01\n" +
	"\x19ConfirmDevelopmentPayment\x12+.locker.v1.ConfirmDevelopmentPaymentRequest\x1a\x15.locker.v1.OrderReply\"B\x82\xd3\xe4\x93\x02<:\x01*\"7/v1/development/orders/{order_id}/payment-confirmations\x12\x86\x01\n" +
	"\rSettleOverdue\x12\x1f.locker.v1.SettleOverdueRequest\x1a\x15.locker.v1.OrderReply\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v1/development/orders/{order_id}/overdue-paymentsB?Z=github.com/rjt001124-dev/smart-parcel-locker/api/locker/v1;v1b\x06proto3"

var (
	file_locker_v1_order_proto_rawDescOnce sync.Once
	file_locker_v1_order_proto_rawDescData []byte
)

func file_locker_v1_order_proto_rawDescGZIP() []byte {
	file_locker_v1_order_proto_rawDescOnce.Do(func() {
		file_locker_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locker_v1_order_proto_rawDesc), len(file_locker_v1_order_proto_rawDesc)))
	})
	return file_locker_v1_order_proto_rawDescData
}

var file_locker_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_locker_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_locker_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),                         // 0: locker.v1.OrderStatus
	(*FeeSnapshot)(nil),                      // 1: locker.v1.FeeSnapshot
	(*Order)(nil),                            // 2: locker.v1.Order
	(*CreateOrderRequest)(nil),               // 3: locker.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),                  // 4: locker.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),                // 5: locker.v1.ListOrdersRequest
	(*ListOrdersReply)(nil),                  // 6: locker.v1.ListOrdersReply
	(*CancelOrderRequest)(nil),               // 7: locker.v1.CancelOrderRequest
	(*OpenDepositDoorRequest)(nil),           // 8: locker.v1.OpenDepositDoorRequest
	(*OpenPickupDoorRequest)(nil),            // 9: locker.v1.OpenPickupDoorRequest
	(*ConfirmDevelopmentPaymentRequest)(nil), // 10: locker.v1.ConfirmDevelopmentPaymentRequest
	(*SettleOverdueRequest)(nil),             // 11: locker.v1.SettleOverdueRequest
	(*OrderReply)(nil),                       // 12: locker.v1.OrderReply
	(CellSize)(0),                            // 13: locker.v1.CellSize
}
var file_locker_v1_order_proto_depIdxs = []int32{
	13, // 0: locker.v1.Order.size:type_name -> locker.v1.CellSize
	0,  // 1: locker.v1.Order.status:type_name -> locker.v1.OrderStatus
	1,  // 2: locker.v1.Order.fee_snapshot:type_name -> locker.v1.FeeSnapshot
	13, // 3: locker.v1.CreateOrderRequest.size:type_name -> locker.v1.CellSize
	2,  // 4: locker.v1.ListOrdersReply.orders:type_name -> locker.v1.Order
	2,  // 5: locker.v1.OrderReply.order:type_name -> locker.v1.Order
	3,  // 6: locker.v1.OrderService.CreateOrder:input_type -> locker.v1.CreateOrderRequest
	4,  // 7: locker.v1.OrderService.GetOrder:input_type -> locker.v1.GetOrderRequest
	5,  // 8: locker.v1.OrderService.ListOrders:input_type -> locker.v1.ListOrdersRequest
	7,  // 9: locker.v1.OrderService.CancelOrder:input_type -> locker.v1.CancelOrderRequest
	8,  // 10: locker.v1.OrderService.OpenDepositDoor:input_type -> locker.v1.OpenDepositDoorRequest
	9,  // 11: locker.v1.OrderService.OpenPickupDoor:input_type -> locker.v1.OpenPickupDoorRequest
	10, // 12: locker.v1.OrderService.ConfirmDevelopmentPayment:input_type -> locker.v1.ConfirmDevelopmentPaymentRequest
	11, // 13: locker.v1.OrderService.SettleOverdue:input_type -> locker.v1.SettleOverdueRequest
	12, // 14: locker.v1.OrderService.CreateOrder:output_type -> locker.v1.OrderReply
	12, // 15: locker.v1.OrderService.GetOrder:output_type -> locker.v1.OrderReply
	6,  // 16: locker.v1.OrderService.ListOrders:output_type -> locker.v1.ListOrdersReply
	12, // 17: locker.v1.OrderService.CancelOrder:output_type -> locker.v1.OrderReply
	12, // 18: locker.v1.OrderService.OpenDepositDoor:output_type -> locker.v1.OrderReply
	12, // 19: locker.v1.OrderService.OpenPickupDoor:output_type -> locker.v1.OrderReply
	12, // 20: locker.v1.OrderService.ConfirmDevelopmentPayment:output_type -> locker.v1.OrderReply
	12, // 21: locker.v1.OrderService.SettleOverdue:output_type -> locker.v1.OrderReply
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_locker_v1_order_proto_init() }
func file_locker_v1_order_proto_init() {
	if File_locker_v1_order_proto != nil {
		return
	}
	file_locker_v1_site_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locker_v1_order_proto_rawDesc), len(file_locker_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locker_v1_order_proto_goTypes,
		DependencyIndexes: file_locker_v1_order_proto_depIdxs,
		EnumInfos:         file_locker_v1_order_proto_enumTypes,
		MessageInfos:      file_locker_v1_order_proto_msgTypes,
	}.Build()
	File_locker_v1_order_proto = out.File
	file_locker_v1_order_proto_goTypes = nil
	file_locker_v1_order_proto_depIdxs = nil
}
