// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: locker/v1/site.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CellSize int32

const (
	CellSize_CELL_SIZE_UNSPECIFIED CellSize = 0
	CellSize_CELL_SIZE_SMALL       CellSize = 1
	CellSize_CELL_SIZE_MEDIUM      CellSize = 2
	CellSize_CELL_SIZE_LARGE       CellSize = 3
)

// Enum value maps for CellSize.
var (
	CellSize_name = map[int32]string{
		0: "CELL_SIZE_UNSPECIFIED",
		1: "CELL_SIZE_SMALL",
		2: "CELL_SIZE_MEDIUM",
		3: "CELL_SIZE_LARGE",
	}
	CellSize_value = map[string]int32{
		"CELL_SIZE_UNSPECIFIED": 0,
		"CELL_SIZE_SMALL":       1,
		"CELL_SIZE_MEDIUM":      2,
		"CELL_SIZE_LARGE":       3,
	}
)

func (x CellSize) Enum() *CellSize {
	p := new(CellSize)
	*p = x
	return p
}

func (x CellSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellSize) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_site_proto_enumTypes[0].Descriptor()
}

func (CellSize) Type() protoreflect.EnumType {
	return &file_locker_v1_site_proto_enumTypes[0]
}

func (x CellSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellSize.Descriptor instead.
func (CellSize) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{0}
}

type CellStatus int32

const (
	CellStatus_CELL_STATUS_UNSPECIFIED CellStatus = 0
	CellStatus_CELL_STATUS_IDLE        CellStatus = 1
	CellStatus_CELL_STATUS_LOCKED      CellStatus = 2
	CellStatus_CELL_STATUS_OCCUPIED    CellStatus = 3
	CellStatus_CELL_STATUS_DISABLED    CellStatus = 4
)

// Enum value maps for CellStatus.
var (
	CellStatus_name = map[int32]string{
		0: "CELL_STATUS_UNSPECIFIED",
		1: "CELL_STATUS_IDLE",
		2: "CELL_STATUS_LOCKED",
		3: "CELL_STATUS_OCCUPIED",
		4: "CELL_STATUS_DISABLED",
	}
	CellStatus_value = map[string]int32{
		"CELL_STATUS_UNSPECIFIED": 0,
		"CELL_STATUS_IDLE":        1,
		"CELL_STATUS_LOCKED":      2,
		"CELL_STATUS_OCCUPIED":    3,
		"CELL_STATUS_DISABLED":    4,
	}
)

func (x CellStatus) Enum() *CellStatus {
	p := new(CellStatus)
	*p = x
	return p
}

func (x CellStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_locker_v1_site_proto_enumTypes[1].Descriptor()
}

func (CellStatus) Type() protoreflect.EnumType {
	return &file_locker_v1_site_proto_enumTypes[1]
}

func (x CellStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellStatus.Descriptor instead.
func (CellStatus) EnumDescriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{1}
}

type City struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *City) Reset() {
	*x = City{}
	mi := &file_locker_v1_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{0}
}

func (x *City) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *City) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

type ListCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesRequest) Reset() {
	*x = ListCitiesRequest{}
	mi := &file_locker_v1_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesRequest) ProtoMessage() {}

func (x *ListCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCitiesRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{1}
}

type ListCitiesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []*City                `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitiesReply) Reset() {
	*x = ListCitiesReply{}
	mi := &file_locker_v1_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitiesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesReply) ProtoMessage() {}

func (x *ListCitiesReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesReply.ProtoReflect.Descriptor instead.
func (*ListCitiesReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{2}
}

func (x *ListCitiesReply) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

type CellAvailability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Size           CellSize               `protobuf:"varint,1,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	AvailableCount int32                  `protobuf:"varint,2,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellAvailability) Reset() {
	*x = CellAvailability{}
	mi := &file_locker_v1_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellAvailability) ProtoMessage() {}

func (x *CellAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellAvailability.ProtoReflect.Descriptor instead.
func (*CellAvailability) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{3}
}

func (x *CellAvailability) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *CellAvailability) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

type SiteSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteNo        string                 `protobuf:"bytes,2,opt,name=site_no,json=siteNo,proto3" json:"site_no,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceM     int32                  `protobuf:"varint,7,opt,name=distance_m,json=distanceM,proto3" json:"distance_m,omitempty"`
	Availability  []*CellAvailability    `protobuf:"bytes,8,rep,name=availability,proto3" json:"availability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteSummary) Reset() {
	*x = SiteSummary{}
	mi := &file_locker_v1_site_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSummary) ProtoMessage() {}

func (x *SiteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSummary.ProtoReflect.Descriptor instead.
func (*SiteSummary) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{4}
}

func (x *SiteSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SiteSummary) GetSiteNo() string {
	if x != nil {
		return x.SiteNo
	}
	return ""
}

func (x *SiteSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SiteSummary) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SiteSummary) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SiteSummary) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SiteSummary) GetDistanceM() int32 {
	if x != nil {
		return x.DistanceM
	}
	return 0
}

func (x *SiteSummary) GetAvailability() []*CellAvailability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type ListSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityCode      string                 `protobuf:"bytes,1,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusM       int32                  `protobuf:"varint,4,opt,name=radius_m,json=radiusM,proto3" json:"radius_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesRequest) Reset() {
	*x = ListSitesRequest{}
	mi := &file_locker_v1_site_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesRequest) ProtoMessage() {}

func (x *ListSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesRequest.ProtoReflect.Descriptor instead.
func (*ListSitesRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{5}
}

func (x *ListSitesRequest) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *ListSitesRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ListSitesRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ListSitesRequest) GetRadiusM() int32 {
	if x != nil {
		return x.RadiusM
	}
	return 0
}

type ListSitesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sites         []*SiteSummary         `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesReply) Reset() {
	*x = ListSitesReply{}
	mi := &file_locker_v1_site_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesReply) ProtoMessage() {}

func (x *ListSitesReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesReply.ProtoReflect.Descriptor instead.
func (*ListSitesReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{6}
}

func (x *ListSitesReply) GetSites() []*SiteSummary {
	if x != nil {
		return x.Sites
	}
	return nil
}

type GetSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteRequest) Reset() {
	*x = GetSiteRequest{}
	mi := &file_locker_v1_site_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteRequest) ProtoMessage() {}

func (x *GetSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteRequest.ProtoReflect.Descriptor instead.
func (*GetSiteRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{7}
}

func (x *GetSiteRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

type GetSiteReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SiteNo            string                 `protobuf:"bytes,2,opt,name=site_no,json=siteNo,proto3" json:"site_no,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address           string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude          float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	OpenTime          string                 `protobuf:"bytes,7,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime         string                 `protobuf:"bytes,8,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	OnlineDeviceCount int32                  `protobuf:"varint,9,opt,name=online_device_count,json=onlineDeviceCount,proto3" json:"online_device_count,omitempty"`
	Availability      []*CellAvailability    `protobuf:"bytes,10,rep,name=availability,proto3" json:"availability,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSiteReply) Reset() {
	*x = GetSiteReply{}
	mi := &file_locker_v1_site_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteReply) ProtoMessage() {}

func (x *GetSiteReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteReply.ProtoReflect.Descriptor instead.
func (*GetSiteReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{8}
}

func (x *GetSiteReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSiteReply) GetSiteNo() string {
	if x != nil {
		return x.SiteNo
	}
	return ""
}

func (x *GetSiteReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSiteReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetSiteReply) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetSiteReply) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetSiteReply) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *GetSiteReply) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *GetSiteReply) GetOnlineDeviceCount() int32 {
	if x != nil {
		return x.OnlineDeviceCount
	}
	return 0
}

func (x *GetSiteReply) GetAvailability() []*CellAvailability {
	if x != nil {
		return x.Availability
	}
	return nil
}

type ListCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        string                 `protobuf:"bytes,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Size          CellSize               `protobuf:"varint,2,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	Status        CellStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=locker.v1.CellStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCellsRequest) Reset() {
	*x = ListCellsRequest{}
	mi := &file_locker_v1_site_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCellsRequest) ProtoMessage() {}

func (x *ListCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCellsRequest.ProtoReflect.Descriptor instead.
func (*ListCellsRequest) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{9}
}

func (x *ListCellsRequest) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *ListCellsRequest) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *ListCellsRequest) GetStatus() CellStatus {
	if x != nil {
		return x.Status
	}
	return CellStatus_CELL_STATUS_UNSPECIFIED
}

type CellView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CellNo        string                 `protobuf:"bytes,2,opt,name=cell_no,json=cellNo,proto3" json:"cell_no,omitempty"`
	Size          CellSize               `protobuf:"varint,3,opt,name=size,proto3,enum=locker.v1.CellSize" json:"size,omitempty"`
	Status        CellStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=locker.v1.CellStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellView) Reset() {
	*x = CellView{}
	mi := &file_locker_v1_site_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellView) ProtoMessage() {}

func (x *CellView) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellView.ProtoReflect.Descriptor instead.
func (*CellView) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{10}
}

func (x *CellView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CellView) GetCellNo() string {
	if x != nil {
		return x.CellNo
	}
	return ""
}

func (x *CellView) GetSize() CellSize {
	if x != nil {
		return x.Size
	}
	return CellSize_CELL_SIZE_UNSPECIFIED
}

func (x *CellView) GetStatus() CellStatus {
	if x != nil {
		return x.Status
	}
	return CellStatus_CELL_STATUS_UNSPECIFIED
}

type ListCellsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*CellView            `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCellsReply) Reset() {
	*x = ListCellsReply{}
	mi := &file_locker_v1_site_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCellsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCellsReply) ProtoMessage() {}

func (x *ListCellsReply) ProtoReflect() protoreflect.Message {
	mi := &file_locker_v1_site_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCellsReply.ProtoReflect.Descriptor instead.
func (*ListCellsReply) Descriptor() ([]byte, []int) {
	return file_locker_v1_site_proto_rawDescGZIP(), []int{11}
}

func (x *ListCellsReply) GetCells() []*CellView {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_locker_v1_site_proto protoreflect.FileDescriptor

const file_locker_v1_site_proto_rawDesc = "" +
	"\n" +
	"\x14locker/v1/site.proto\x12\tlocker.v1\x1a\x1cgoogle/api/annotations.proto\"Z\n" +
	"\x04City\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\"\x13\n" +
	"\x11ListCitiesRequest\":\n" +
	"\x0fListCitiesReply\x12'\n" +
	"\x06cities\x18\x01 \x03(\v2\x0f.locker.v1.CityR\x06cities\"d\n" +
	"\x10CellAvailability\x12'\n" +
	"\x04size\x18\x01 \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12'\n" +
	"\x0favailable_count\x18\x02 \x01(\x05R\x0eavailableCount\"\xfe\x01\n" +
	"\vSiteSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\asite_no\x18\x02 \x01(\tR\x06siteNo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"distance_m\x18\a \x01(\x05R\tdistanceM\x12?\n" +
	"\favailability\x18\b \x03(\v2\x1b.locker.v1.CellAvailabilityR\favailability\"\x84\x01\n" +
	"\x10ListSitesRequest\x12\x1b\n" +
	"\tcity_code\x18\x01 \x01(\tR\bcityCode\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bradius_m\x18\x04 \x01(\x05R\aradiusM\">\n" +
	"\x0eListSitesReply\x12,\n" +
	"\x05sites\x18\x01 \x03(\v2\x16.locker.v1.SiteSummaryR\x05sites\")\n" +
	"\x0eGetSiteRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\"\xcc\x02\n" +
	"\fGetSiteReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\asite_no\x18\x02 \x01(\tR\x06siteNo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\topen_time\x18\a \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\b \x01(\tR\tcloseTime\x12.\n" +
	"\x13online_device_count\x18\t \x01(\x05R\x11onlineDeviceCount\x12?\n" +
	"\favailability\x18\n" +
	" \x03(\v2\x1b.locker.v1.CellAvailabilityR\favailability\"\x83\x01\n" +
	"\x10ListCellsRequest\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\tR\x06siteId\x12'\n" +
	"\x04size\x18\x02 \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.locker.v1.CellStatusR\x06status\"\x8b\x01\n" +
	"\bCellView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acell_no\x18\x02 \x01(\tR\x06cellNo\x12'\n" +
	"\x04size\x18\x03 \x01(\x0e2\x13.locker.v1.CellSizeR\x04size\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.locker.v1.CellStatusR\x06status\";\n" +
	"\x0eListCellsReply\x12)\n" +
	"\x05cells\x18\x01 \x03(\v2\x13.locker.v1.CellViewR\x05cells*e\n" +
	"\bCellSize\x12\x19\n" +
	"\x15CELL_SIZE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCELL_SIZE_SMALL\x10\x01\x12\x14\n" +
	"\x10CELL_SIZE_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fCELL_SIZE_LARGE\x10\x03*\x8b\x01\n" +
	"\n" +
	"CellStatus\x12\x1b\n" +
	"\x17CELL_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CELL_STATUS_IDLE\x10\x01\x12\x16\n" +
	"\x12CELL_STATUS_LOCKED\x10\x02\x12\x18\n" +
	"\x14CELL_STATUS_OCCUPIED\x10\x03\x12\x18\n" +
	"\x14CELL_STATUS_DISABLED\x10\x042\x85\x03\n" +
	"\vSiteService\x12Z\n" +
	"\n" +
	"ListCities\x12\x1c.locker.v1.ListCitiesRequest\x1a\x1a.locker.v1.ListCitiesReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/cities\x12V\n" +
	"\tListSites\x12\x1b.locker.v1.ListSitesRequest\x1a\x19.locker.v1.ListSitesReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/sites\x12Z\n" +
	"\aGetSite\x12\x19.locker.v1.GetSiteRequest\x1a\x17.locker.v1.GetSiteReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/sites/{site_id}\x12f\n" +
	"\tListCells\x12\x1b.locker.v1.ListCellsRequest\x1a\x19.locker.v1.ListCellsReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/sites/{site_id}/cellsB?Z=github.com/rjt001124-dev/smart-parcel-locker/api/locker/v1;v1b\x06proto3"

var (
	file_locker_v1_site_proto_rawDescOnce sync.Once
	file_locker_v1_site_proto_rawDescData []byte
)

func file_locker_v1_site_proto_rawDescGZIP() []byte {
	file_locker_v1_site_proto_rawDescOnce.Do(func() {
		file_locker_v1_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_locker_v1_site_proto_rawDesc), len(file_locker_v1_site_proto_rawDesc)))
	})
	return file_locker_v1_site_proto_rawDescData
}

var file_locker_v1_site_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_locker_v1_site_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_locker_v1_site_proto_goTypes = []any{
	(CellSize)(0),             // 0: locker.v1.CellSize
	(CellStatus)(0),           // 1: locker.v1.CellStatus
	(*City)(nil),              // 2: locker.v1.City
	(*ListCitiesRequest)(nil), // 3: locker.v1.ListCitiesRequest
	(*ListCitiesReply)(nil),   // 4: locker.v1.ListCitiesReply
	(*CellAvailability)(nil),  // 5: locker.v1.CellAvailability
	(*SiteSummary)(nil),       // 6: locker.v1.SiteSummary
	(*ListSitesRequest)(nil),  // 7: locker.v1.ListSitesRequest
	(*ListSitesReply)(nil),    // 8: locker.v1.ListSitesReply
	(*GetSiteRequest)(nil),    // 9: locker.v1.GetSiteRequest
	(*GetSiteReply)(nil),      // 10: locker.v1.GetSiteReply
	(*ListCellsRequest)(nil),  // 11: locker.v1.ListCellsRequest
	(*CellView)(nil),          // 12: locker.v1.CellView
	(*ListCellsReply)(nil),    // 13: locker.v1.ListCellsReply
}
var file_locker_v1_site_proto_depIdxs = []int32{
	2,  // 0: locker.v1.ListCitiesReply.cities:type_name -> locker.v1.City
	0,  // 1: locker.v1.CellAvailability.size:type_name -> locker.v1.CellSize
	5,  // 2: locker.v1.SiteSummary.availability:type_name -> locker.v1.CellAvailability
	6,  // 3: locker.v1.ListSitesReply.sites:type_name -> locker.v1.SiteSummary
	5,  // 4: locker.v1.GetSiteReply.availability:type_name -> locker.v1.CellAvailability
	0,  // 5: locker.v1.ListCellsRequest.size:type_name -> locker.v1.CellSize
	1,  // 6: locker.v1.ListCellsRequest.status:type_name -> locker.v1.CellStatus
	0,  // 7: locker.v1.CellView.size:type_name -> locker.v1.CellSize
	1,  // 8: locker.v1.CellView.status:type_name -> locker.v1.CellStatus
	12, // 9: locker.v1.ListCellsReply.cells:type_name -> locker.v1.CellView
	3,  // 10: locker.v1.SiteService.ListCities:input_type -> locker.v1.ListCitiesRequest
	7,  // 11: locker.v1.SiteService.ListSites:input_type -> locker.v1.ListSitesRequest
	9,  // 12: locker.v1.SiteService.GetSite:input_type -> locker.v1.GetSiteRequest
	11, // 13: locker.v1.SiteService.ListCells:input_type -> locker.v1.ListCellsRequest
	4,  // 14: locker.v1.SiteService.ListCities:output_type -> locker.v1.ListCitiesReply
	8,  // 15: locker.v1.SiteService.ListSites:output_type -> locker.v1.ListSitesReply
	10, // 16: locker.v1.SiteService.GetSite:output_type -> locker.v1.GetSiteReply
	13, // 17: locker.v1.SiteService.ListCells:output_type -> locker.v1.ListCellsReply
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_locker_v1_site_proto_init() }
func file_locker_v1_site_proto_init() {
	if File_locker_v1_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_locker_v1_site_proto_rawDesc), len(file_locker_v1_site_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_locker_v1_site_proto_goTypes,
		DependencyIndexes: file_locker_v1_site_proto_depIdxs,
		EnumInfos:         file_locker_v1_site_proto_enumTypes,
		MessageInfos:      file_locker_v1_site_proto_msgTypes,
	}.Build()
	File_locker_v1_site_proto = out.File
	file_locker_v1_site_proto_goTypes = nil
	file_locker_v1_site_proto_depIdxs = nil
}
