// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: locker/v1/site.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSiteServiceGetSite = "/locker.v1.SiteService/GetSite"
const OperationSiteServiceListCells = "/locker.v1.SiteService/ListCells"
const OperationSiteServiceListCities = "/locker.v1.SiteService/ListCities"
const OperationSiteServiceListSites = "/locker.v1.SiteService/ListSites"

type SiteServiceHTTPServer interface {
	GetSite(context.Context, *GetSiteRequest) (*GetSiteReply, error)
	ListCells(context.Context, *ListCellsRequest) (*ListCellsReply, error)
	ListCities(context.Context, *ListCitiesRequest) (*ListCitiesReply, error)
	ListSites(context.Context, *ListSitesRequest) (*ListSitesReply, error)
}

func RegisterSiteServiceHTTPServer(s *http.Server, srv SiteServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/cities", _SiteService_ListCities0_HTTP_Handler(srv))
	r.GET("/v1/sites", _SiteService_ListSites0_HTTP_Handler(srv))
	r.GET("/v1/sites/{site_id}", _SiteService_GetSite0_HTTP_Handler(srv))
	r.GET("/v1/sites/{site_id}/cells", _SiteService_ListCells0_HTTP_Handler(srv))
}

func _SiteService_ListCities0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCitiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceListCities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCities(ctx, req.(*ListCitiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCitiesReply)
		return ctx.Result(200, reply)
	}
}

func _SiteService_ListSites0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSitesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceListSites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSites(ctx, req.(*ListSitesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSitesReply)
		return ctx.Result(200, reply)
	}
}

func _SiteService_GetSite0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSiteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceGetSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSite(ctx, req.(*GetSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSiteReply)
		return ctx.Result(200, reply)
	}
}

func _SiteService_ListCells0_HTTP_Handler(srv SiteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCellsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteServiceListCells)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCells(ctx, req.(*ListCellsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCellsReply)
		return ctx.Result(200, reply)
	}
}

type SiteServiceHTTPClient interface {
	GetSite(ctx context.Context, req *GetSiteRequest, opts ...http.CallOption) (rsp *GetSiteReply, err error)
	ListCells(ctx context.Context, req *ListCellsRequest, opts ...http.CallOption) (rsp *ListCellsReply, err error)
	ListCities(ctx context.Context, req *ListCitiesRequest, opts ...http.CallOption) (rsp *ListCitiesReply, err error)
	ListSites(ctx context.Context, req *ListSitesRequest, opts ...http.CallOption) (rsp *ListSitesReply, err error)
}

type SiteServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSiteServiceHTTPClient(client *http.Client) SiteServiceHTTPClient {
	return &SiteServiceHTTPClientImpl{client}
}

func (c *SiteServiceHTTPClientImpl) GetSite(ctx context.Context, in *GetSiteRequest, opts ...http.CallOption) (*GetSiteReply, error) {
	var out GetSiteReply
	pattern := "/v1/sites/{site_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSiteServiceGetSite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) ListCells(ctx context.Context, in *ListCellsRequest, opts ...http.CallOption) (*ListCellsReply, error) {
	var out ListCellsReply
	pattern := "/v1/sites/{site_id}/cells"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSiteServiceListCells))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) ListCities(ctx context.Context, in *ListCitiesRequest, opts ...http.CallOption) (*ListCitiesReply, error) {
	var out ListCitiesReply
	pattern := "/v1/cities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSiteServiceListCities))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SiteServiceHTTPClientImpl) ListSites(ctx context.Context, in *ListSitesRequest, opts ...http.CallOption) (*ListSitesReply, error) {
	var out ListSitesReply
	pattern := "/v1/sites"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSiteServiceListSites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
